Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -26,6 +26,10 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
+    - name: Cleanup Docker resources to free disk space
+      run: |
+        docker system prune -af || echo "Docker cleanup failed or no resources to prune"
+
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
@@ -37,20 +41,12 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y unzip
-
+    
     - name: Install AWS CLI
       run: |
-        if aws --version; then
-          echo "AWS CLI is already installed. Updating..."
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install --update
-        else
-          echo "Installing AWS CLI..."
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
-        fi
+        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+        unzip awscliv2.zip
+        sudo ./aws/install
         aws --version
 
     - name: Create Amazon ECR repository if it does not exist
